apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: fjernlys
  name: fjernlys
  namespace: fjernlys
spec:
  ingresses:
    - https://fjernlys.ansatt.dev.nav.no
  image: {{ image }}
  port: 3000
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 200m
      memory: 128Mi
